src/main/default/objects/WSDispatcherSetting__c/WSDispatcherSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains details regarding WebSocket dispatcher callout</description>
    <label>WS Dispatcher Setting</label>
</CustomObject>

src/main/default/objects/WSDispatcherSetting__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>WebSocket dispatcher endpoint</description>
    <inlineHelpText>WebSocket dispatcher endpoint</inlineHelpText>
    <label>Endpoint</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/WSDispatcherSetting__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>50000</defaultValue>
    <description
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</description>
    <inlineHelpText
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/ws-dispatcher/WSDispatcherSettings.cls
public class WSDispatcherSettings {
    public static final Integer HTTP_MAX_TIMEOUT = 120000;
    public static final Integer CPU_TIME_SCOPE = 3000;

    @TestVisible
    private static WSDispatcherSetting__c settings = WSDispatcherSetting__c.getOrgDefaults();

    public static String getEndpoint() {
        String settingValue = settings.Endpoint__c;
        if (String.isBlank(settingValue)) {
            throw new CalloutException('No endpoint has been provided in the WS Dispatcher Settings');
        }
        return settingValue;
    }

    public static Integer getTimeout() {
        Integer settingValue = settings.Timeout__c?.intValue();
        if (settingValue == null || settingValue > HTTP_MAX_TIMEOUT) {
            System.debug(
                LoggingLevel.WARN,
                'No timeout has been specified in the WS Dispatcher Settings. Consider using max timeout'
            );
            settingValue = HTTP_MAX_TIMEOUT;
        }
        return settingValue;
    }
}