src/main/default/objects/WSDispatcherSetting__c/WSDispatcherSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains details regarding WebSocket dispatcher callout</description>
    <label>WS Dispatcher Setting</label>
</CustomObject>

src/main/default/objects/WSDispatcherSetting__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>WebSocket dispatcher endpoint</description>
    <inlineHelpText>WebSocket dispatcher endpoint</inlineHelpText>
    <label>Endpoint</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/WSDispatcherSetting__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>50000</defaultValue>
    <description
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</description>
    <inlineHelpText
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/test/classes/WSDispatcherSettingsTest.cls
@IsTest(IsParallel = true)
private class WSDispatcherSettingsTest {
    @IsTest
    private static void getEndpointPositiveTest() {
        String endpoint = 'https://fake.ws-dispatcher.com/ws';
        initSetting(endpoint, 30000);

        String result = WSDispatcherSettings.getEndpoint();

        System.assertEquals(endpoint, result, 'Did not receive the valid endpoint');
    }

    @IsTest
    private static void getEndpointNoValueTest() {
        Exception error;
        try {
            String result = WSDispatcherSettings.getEndpoint();
        } catch (Exception ex) {
            error = ex;
        }

        System.assert(error != null, 'No exception has been thrown');
        System.assert(error instanceof IllegalArgumentException, 'Invalid exception type');
    }

    @IsTest
    private static void getTimeoutPositiveTest() {
        Integer timeout = 50000;
        initSetting('https://fake.ws-dispatcher.com/ws', timeout);

        Integer result = WSDispatcherSettings.getTimeout();

        System.assertEquals(timeout, result, 'Did not receive the valid timeout');
    }

    @IsTest
    private static void getTimeoutNoValueTest() {
        Integer result = WSDispatcherSettings.getTimeout();
        System.assertEquals(WSDispatcherSettings.HTTP_DEFAULT_TIMEOUT, result, 'Did not receive the valid timeout');
    }

    @IsTest
    private static void getTimeoutInvalidValueTest() {
        initSetting('https://fake.ws-dispatcher.com/ws', 1000);

        Exception error;
        try {
            Integer result = WSDispatcherSettings.getTimeout();
        } catch (Exception ex) {
            error = ex;
        }

        System.assert(error != null, 'No exception has been thrown');
        System.assert(error instanceof IllegalArgumentException, 'Invalid exception type');
    }

    private static void initSetting(String endpoint, Integer timeout) {
        insert new WSDispatcherSetting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Timeout__c = timeout,
            Endpoint__c = endpoint
        );
    }
}