src/main/default/objects/WSDispatcherSetting__c/WSDispatcherSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains details regarding WebSocket dispatcher callout</description>
    <label>WS Dispatcher Setting</label>
</CustomObject>

src/main/default/objects/WSDispatcherSetting__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>WebSocket dispatcher endpoint</description>
    <inlineHelpText>WebSocket dispatcher endpoint</inlineHelpText>
    <label>Endpoint</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/WSDispatcherSetting__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>50000</defaultValue>
    <description
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</description>
    <inlineHelpText
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/test/classes/WSClientTest.cls
@IsTest(IsParallel=true)
public class WSClientTest {
    @TestSetup
    private static void init() {
        insert new WSDispatcherSetting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Timeout__c = 50000,
            Endpoint__c = 'https://fake.ws-dispatcher.com/ws'
        );
    }

    @IsTest
    private static void connectWithNoHandlersAndJustMessageAndCloseTest() {
        Test.setMock(HttpCalloutMock.class, new WSDispatcherHttpMock());
        Test.startTest();
        WSConnection connection = new WSClient().connect('wss://fake.ws.endpoint/');
        connection.send('Hello World!');
        connection.close();
        Test.stopTest();
    }

    @IsTest
    private static void connectFailedTest() {
        Test.setMock(
            HttpCalloutMock.class,
            new WSDispatcherHttpMock(WSResponsePayload.ResponseEvent.Error, 'Unable to connect')
        );
        Exception error;
        Test.startTest();
        try {
            new WSClient().connect('wss://fake.ws.endpoint/');
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        System.assert(error != null, 'Exception should have been thrown');
        System.assert(error instanceof WSConnection.ConnectionException, 'Exception type is not correct');
        System.assertEquals(
            'Failed to connect: Unable to connect',
            error.getMessage(),
            'Exception message is not correct'
        );
    }

    @IsTest
    private static void connectWithMessageAndErrorAndCloseHandlersTest() {
        Test.setMock(
            HttpCalloutMock.class,
            new WSDispatcherHttpMock(WSResponsePayload.ResponseEvent.Message, 'Hello World!')
        );
        Test.startTest();
        WSConnection connection = new WSClient()
            .onMessage(WSClientTest.MockUpdateHandler.class)
            .onMessage(WSClientTest.MockUpdateHandler.class, new Map<String, Object>{ 'test' => 1 })
            .onError(WSClientTest.MockUpdateHandler.class)
            .onError(WSClientTest.MockUpdateHandler.class, new Map<String, Object>{ 'test' => 2 })
            .onClose(WSClientTest.MockUpdateHandler.class)
            .onClose(WSClientTest.MockUpdateHandler.class, new Map<String, Object>{ 'test' => 3 })
            .connect('wss://fake.ws.endpoint/');
        Test.getEventBus().deliver();
        Test.stopTest();
        // Right now there is no way to test this kind of scenario:
        // In this case we start Queueable job which publishes events and event trigger starts a new job
        // Even Test.startTest(), Test.startTest() and Test.getEventBus().deliver() don't work with this scenario
    }

    public class MockUpdateHandler implements IWSMessageHandler {
        public void handle(WSConnection connection, Map<String, Object> args) {
        }
    }
}