src/main/default/objects/WSDispatcherSetting__c/WSDispatcherSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains details regarding WebSocket dispatcher callout</description>
    <label>WS Dispatcher Setting</label>
</CustomObject>

src/main/default/objects/WSDispatcherSetting__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>WebSocket dispatcher endpoint</description>
    <inlineHelpText>WebSocket dispatcher endpoint</inlineHelpText>
    <label>Endpoint</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/WSDispatcherSetting__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>50000</defaultValue>
    <description
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</description>
    <inlineHelpText
    >Calling timeout; Shouldn&apos;t be more than 60000 since this is an Apex async transaction limit</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/test/classes/WSConnectionTest.cls
@IsTest(IsParallel=true)
private class WSConnectionTest {
    private static final String CLIENT_ID = 'eb3e9a51-f7a3-493b-b208-fae170374e8e';

    @TestSetup
    private static void init() {
        insert new WSDispatcherSetting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Timeout__c = 50000,
            Endpoint__c = 'https://fake.ws-dispatcher.com/ws'
        );
    }

    @IsTest
    private static void checkClientIdAndMessagesTest() {
        WSConnection connection = new WSConnection(CLIENT_ID);
        System.assert(connection.getUpdates().isEmpty(), 'There should be no updates');
        System.assertEquals(CLIENT_ID, connection.getClientId(), 'Client id is not correct');
    }

    @IsTest
    private static void sendMessageTest() {
        Test.setMock(HttpCalloutMock.class, new WSDispatcherHttpMock());
        Test.startTest();
        new WSConnection(CLIENT_ID).send('Hello World!');
        Test.stopTest();
    }

    @IsTest
    private static void sendMessageWithInvalidClientIdTest() {
        Test.setMock(
            HttpCalloutMock.class,
            new WSDispatcherHttpMock(WSResponsePayload.ResponseEvent.Error, 'Invalid client id')
        );
        Exception error;
        Test.startTest();
        try {
            new WSConnection(CLIENT_ID).send('Hello World!');
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        System.assert(error != null, 'Exception should have been thrown');
        System.assert(error instanceof WSConnection.ConnectionException, 'Exception type is not correct');
        System.assertEquals(
            'Failed to send a message: Invalid client id',
            error.getMessage(),
            'Exception message is not correct'
        );
    }

    @IsTest
    private static void closeConnectionTest() {
        Test.setMock(HttpCalloutMock.class, new WSDispatcherHttpMock());
        Test.startTest();
        new WSConnection(CLIENT_ID).close();
        Test.stopTest();
    }

    @IsTest
    private static void closeConnectionWithInvalidClientIdTest() {
        Test.setMock(
            HttpCalloutMock.class,
            new WSDispatcherHttpMock(WSResponsePayload.ResponseEvent.Error, 'Invalid client id')
        );
        Exception error;
        Test.startTest();
        try {
            new WSConnection(CLIENT_ID).close();
        } catch (Exception ex) {
            error = ex;
        }
        Test.stopTest();

        System.assert(error != null, 'Exception should have been thrown');
        System.assert(error instanceof WSConnection.ConnectionException, 'Exception type is not correct');
        System.assertEquals(
            'Failed to close the connection: Invalid client id',
            error.getMessage(),
            'Exception message is not correct'
        );
    }
}