src/main/default/objects/WSListenEvent__e/WSListenEvent__e.object-meta.xml
<CustomObject>
    <description>Event for starting a new listen job in order to receive updates from a WebSocket server</description>
    <label>WS Listen Event</label>
    <pluralLabel>WS Listen Events</pluralLabel>
</CustomObject>

src/main/default/objects/WSListenEvent__e/fields/Handlers__c.field-meta.xml
<CustomField>
    <fullName>Handlers__c</fullName>
    <description>JSON serialised handlers list for listening to upcoming updates</description>
    <label>Handlers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/classes/ws-dispatcher/WSDispatcherService.cls
public class WSDispatcherService {
    public static WSResponsePayload connect(String endpoint, String protocol) {
        return call(new WSRequestPayload(WSRequestPayload.RequestCommand.Connect, endpoint, protocol));
    }

    public static WSResponsePayload listen(String clientId) {
        return call(new WSRequestPayload(WSRequestPayload.RequestCommand.Listen, clientId));
    }

    public static void listenAsync(String clientId, List<WSHandlerWrapper> handlers) {
        publishListenEvent(clientId, handlers);
    }

    public static WSResponsePayload message(String clientId, String message) {
        return call(new WSRequestPayload(WSRequestPayload.RequestCommand.Message, clientId, message));
    }

    public static WSResponsePayload close(String clientId) {
        return call(new WSRequestPayload(WSRequestPayload.RequestCommand.Close, clientId));
    }

    private static WSResponsePayload call(WSRequestPayload payload) {
        HttpRequest request = new HttpRequest();
        request.setEndpoint(WSDispatcherSettings.getEndpoint());
        request.setTimeout(WSDispatcherSettings.getTimeout());
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(payload.toJson());
        return WSResponsePayload.fromJson(new Http().send(request).getBody());
    }

    private static void publishListenEvent(String clientId, List<WSHandlerWrapper> handlers) {
        EventBus.publish(new WSListenEvent__e(ClientId__c = clientId, Handlers__c = JSON.serialize(handlers)));
    }
}