src/main/default/objects/WSUpdate__e/WSUpdate__e.object-meta.xml
<CustomObject>
    <description>Indicates updates (messages, errors or closing request) coming from WebSocket server</description>
    <label>WS Update</label>
    <pluralLabel>WS Updates</pluralLabel>
</CustomObject>

src/main/default/objects/WSUpdate__e/fields/Arguments__c.field-meta.xml
<CustomField>
    <fullName>Arguments__c</fullName>
    <description>JSON serialised parameters list passed to the handler</description>
    <label>Arguments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/WSUpdate__e/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>UUID WebSocket client identifier</description>
    <label>Client Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/WSUpdate__e/fields/Messages__c.field-meta.xml
<CustomField>
    <fullName>Messages__c</fullName>
    <description>JSON serialised messages list received from the WebSocket server</description>
    <label>Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/classes/trigger-handlers/WSUpdateEventHandler.cls
public class WSUpdateEventHandler extends WSAsyncJob {
    private final List<WSUpdate__e> events;

    public WSUpdateEventHandler(List<WSUpdate__e> events) {
        this.events = events;
    }

    public void handle() {
        WSAsyncJob.run(this);
    }

    public override void execute() {
        for (WSUpdate__e event : events) {
            WSConnection connection = createConnection(event);
            Map<String, Object> args = (Map<String, Object>) JSON.deserializeUntyped(event.Arguments__c);
            WSMessageHandler handler = (WSMessageHandler) Type.forName(event.HandlerClassName__c).newInstance();
            handler.handle(connection, args);
        }
    }

    private WSConnection createConnection(WSUpdate__e event) {
        return new WSConnection(
            event.ClientId__c,
            (List<String>) JSON.deserialize(event.Messages__c, List<String>.class)
        );
    }
}