src/main/default/objects/WSUpdate__e/WSUpdate__e.object-meta.xml
<CustomObject>
    <description>Indicates updates (messages, errors or closing request) coming from WebSocket server</description>
    <label>WS Update</label>
    <pluralLabel>WS Updates</pluralLabel>
</CustomObject>

src/main/default/objects/WSUpdate__e/fields/Arguments__c.field-meta.xml
<CustomField>
    <fullName>Arguments__c</fullName>
    <description>JSON serialised parameters list passed to the handler</description>
    <label>Arguments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/WSUpdate__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Message, Error or Close</description>
    <label>Type</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/handlers/NotificationHandler.cls
public class NotificationHandler {
    private final NotificationType type;
    private final String className;
    private final Map<String, Object> args;

    public NotificationHandler(NotificationType type, String className, Map<String, Object> args) {
        this.type = type;
        this.className = className;
        this.args = args == null ? new Map<String, Object>() : args;
    }

    public Boolean ofType(String typeName) {
        try {
            return type == NotificationType.valueOf(typeName);
        } catch (NoSuchElementException ex) {
            return false;
        }
    }

    public WSUpdate__e toEvent() {
        return new WSUpdate__e(Type__c = type, HandlerClassName__c = className, Arguments__c = JSON.serialize(args));
    }

    public enum NotificationType {
        Message,
        Error,
        Close
    }
}